### ISSUE TITLE
Feedback Repository - Marco Fijan

### ISSUE THREAD

**Issue by marcoFijan** [NathanNeelis/frontend-data#1]
Checks:
* Reponame correct
* Gitignore exists
* Link to live gihub pages works!
* Description aanwezig: leuke gif!
* Concept duidelijk
* Afbeelding aanwezig
* Gebruikte en benodigde data duidelijk
* Resources aanwezig
* **Nog geen link met de voorbeeld data die je hebt gebruikt**

Pluspunten:
* Leuke gif. Laat je readme echt mooi overkomen
* Getting started guide duidelijk en overzichtelijk
* Erg goed om License aan te geven
* Resources erg goed georganiseerd, dat is bij mij nog een zooitje
* Code goed opgebouwd met duidelijke benamingen voor je functions en variablen 

Aandachtspunten
* In de readme nog even links zetten met de voorbeeld data die je hebt gebruikt
* In je code bij Credits naar Laurens ook de link zetten van de gebruikte vizhub van Laurens
* Misschien elke function in je code nog even voorzien van een comment. Wat doet deze function precies?

**Comment by NathanNeelis** [comment]
* Link toegevoegd naar voorbeeld data
* Laurens voorbeeld ook toegevoegd aan credits
* ga me resources later nog een beetje extra updaten
* Ja ik ga nog iets meer comments schrijven.
