### ISSUE TITLE
Feedback Wiki - Marco Fijan

### ISSUE THREAD

**Issue by marcoFijan** [NathanNeelis/frontend-data#2]
Checks
* Duidelijk gedetaileerde beschrijving over de opschoning van data
* Zijn genoeg pagina's die weergeven wat de student geleerd heeft
* **Nog niet specifiek de updata pattern uitgelegd**
* **Kan niet makkelijk een before-after vergelijking zien van het opschonen van data**

Pluspunten
* Erg goed dat je de d3 Visual afbeeldingen hebt verzameld! Laat erg goed je proces zien

Tips
* Je sidebar zou ik niet ook nog eens in je home plakken. Zeker met die icoontjes wordt het erg druk op die manier. Of haal de icoontjes weg uit de home
* Misschien past D3 Visual beter onder Process in plaats van Learning Progress? 
* Misschien kan er 1 algemene subtitel bedacht worden voor Process en Learning Progress.

**Comment by NathanNeelis** [comment]
* Update pattern is nu uitgelegd in D3 visual
* Misschien moet ik nog de naam aanpassen naar iets wat passender is.
* Heb geprobeerd de before-after iets duidelijker te maken met stappen. Maar het is gewoon heel veel, en daarom wordt het een beetje onduidelijk. Als iemand er echt door heen zou lezen zou het denk ik wel duidelijk zijn.
* 1 subtitel gemaakt bedankt voor de tip.

Thanks voor de feedback!
