### ISSUE TITLE
Feedback Live Demo - Marco Fijan

### ISSUE THREAD

**Issue by marcoFijan** [NathanNeelis/frontend-data#3]
Checks 
* Labels, assen en titels zijn te begrijpen, maar de titel is nog een beetje verwarrend met de visualisatie (zie tip #3)
* Interactie ziet er mooi en duidelijk uit!

Pluspunten
* Mooie vormgeving!
* Interessante en orginele vraagstelling
* Leuke transities!

Tips
* Maak een label van de tekst bij de checkbox. Dan kan er ook op de label geklikt worden als je de data wilt veranderen
* Misschien nog een x-as label toevoegen? De titel is in het engels dus vooral wanneer je randstad steden laat zien (die Nederlands zijn), is het misschien handig om toch een x-as label te weergeven die 'cities' aangeeft
* Het lijkt alsof de titel deze vraag stelt: Welke randstad **maakt het meest gebruik** van de P+R parkeerplaatsen om auto's uit het centrum te houden. Bij het beantwoorden van deze vraag verwacht ik dan een vergelijking of verhouding met normale parkeerplaatsen. Misschien een idee om ipv 'uses' te gebruiken 'has' te gebruiken. Dus: _Which Randstad city has the most Park and Ride parking areas to keep cars from their city center?_ Het is maar een ideetje, maar wanneer ik 'uses', ofterwijl 'gebruiken' lees, verwacht ik een vergelijking zodat je de verhouding en percentage kunt vergelijken.
* Misschien heb je nog tijd voor leuke hover-effecten

**Comment by NathanNeelis** [comment]
* Titel aangepast. Thanks for the tip!  
* Checkbox heb ik nu gestyled. Stond nog op me ToDo lijstje. 
* X-as laat ik voor nu zitten, ik vind de as persoonlijk duidelijk genoeg. Geeft naar mijn mening alleen maar meer ruis.
* Hover zou nog leuk zijn, misschien vanavond nog als ik tijd heb.
